### PR TITLE
Logbook

### PR DESCRIPTION
**Pull request by gdude2002**
This is more so we can keep the comments on this branch together, but we'll need to merge it at some point!

### CODE REVIEW

**Comment by gdude2002** [comment]
**Don't actually merge this yet, it's not finished**

**Comment by gdude2002** [comment]
As far as I can see, this one is done. Awaiting review.

**Comment by gdude2002** [comment]
Although this is blocked until @rakiru reviews it, I may merge it regardless soon since I'm pretty confident this code is fine.

**Comment by rakiru** [comment]
I've had a quick scan, and it looks fine, but I won't have time to look at it in detail for a couple days. Feel free to merge if you want.

**Comment by gdude2002** [comment]
That's fine, I mostly wanted to confirm that it wasn't stupid code/concepts. Thanks.

**Pull request merged**
